language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
services:
  - mongodb
sudo: false
env:
  - CXX=g++-4.8
language: node_js
node_js:
  - "4"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
